version: '2'
services:
  mongo-db:
    image: mongo:latest
    volumes:
      - /data/db
      - ./dump:/dump
    expose:
      - "27017"
    ports:
      - "27017:27017"

  mongo-bi:
    build: .
    ports:
      - 9015:3307
    depends_on:
      - mongo-db
    links:
      - mongo-db
    environment:
      - DB_NAME=mongo
      - MONGO_HOST=mongo-db
      - MONGO_PORT=27017  
